name: Update v2rayN nodes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "test $(date)" > v2rayN_nodes.txt

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git checkout -B nodes

          git add v2rayN_nodes.txt
          git commit -m "update nodes"

          git push origin nodes --force
