name: Test Push

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "test $(date)" > v2rayN_nodes.txt

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add v2rayN_nodes.txt
          git commit -m "test push from actions"

          git push origin HEAD:main --force
