name: Update v2rayN nodes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - run: |
          python fetch_nodes.py

          git config user.name "JohnnyW081"
          git config user.email "actions@github.com"

          git pull --rebase origin main

          git add v2rayN_nodes.txt
          git commit -m "auto update v2rayN nodes" || echo "no changes"

          git push origin main
